/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Macbook.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Macbook.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[4.076, 5.904, -1.005]} rotation={[1.89, 0.881, -2.045]} />
        <group name="Camera" position={[7.359, 4.958, 6.926]} rotation={[1.242, 0.33, -0.76]} />
        <group name="Macbook" position={[0, 0.519, 0]} rotation={[-Math.PI, 0.199, -Math.PI]} scale={0.103}>
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Frame.001']} />
          <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials.HeadPhoneHole} />
          <mesh name="Circle001_2" geometry={nodes.Circle001_2.geometry} material={materials.USB_C_INSIDE} />
          <mesh name="Circle001_3" geometry={nodes.Circle001_3.geometry} material={materials.TouchbarBorder} />
          <mesh name="Circle001_4" geometry={nodes.Circle001_4.geometry} material={materials.Keyboard} />
          <group name="Bottom" position={[0, -0.509, 0]} scale={5.796}>
            <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['Frame.001']} />
            <mesh name="Circle006_1" geometry={nodes.Circle006_1.geometry} material={materials.USB_C_INSIDE} />
          </group>
          <mesh name="FrontCameraRing001" geometry={nodes.FrontCameraRing001.geometry} material={materials['CameraRIngBlack.002']} position={[-0.155, 19.571, -16.151]} scale={5.796} />
          <group name="Keyboard" position={[-11.786, -0.15, -8.301]} scale={5.796}>
            <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Keyboard.001']} />
            <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials.Key} />
            <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={materials.Touchbar} />
          </group>
          <mesh name="KeyboardKeyHole" geometry={nodes.KeyboardKeyHole.geometry} material={materials['Keyboard.001']} position={[-11.786, -0.152, -8.301]} scale={5.796} />
          <mesh name="RubberFoot" geometry={nodes.RubberFoot.geometry} material={materials.DarkRubber} position={[-11.951, -0.751, 7.857]} scale={5.796} />
          <group name="ScreenHinge" position={[0.011, -0.211, -10.559]} scale={5.796}>
            <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials.HingeBlack} />
            <mesh name="Circle012_1" geometry={nodes.Circle012_1.geometry} material={materials.HingeMetal} />
          </group>
          <group name="SpeakerLeft" position={[-15.026, 0.031, 0.604]} scale={5.796}>
            <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials['Frame.001']} />
            <mesh name="Circle009_1" geometry={nodes.Circle009_1.geometry} material={materials.SpeakerHole} />
          </group>
          <group name="SpeakerRight" position={[12.204, 0.031, 0.604]} scale={5.796}>
            <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Frame.001']} />
            <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials.SpeakerHole} />
          </group>
          <group name="Top" position={[0.007, -0.472, -10.412]} rotation={[-Math.PI, 0, 0]} scale={5.796}>
            <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Frame.002']} />
            <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials.Screen} />
            <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials.ScreenGlass} />
            <mesh name="Circle002_3" geometry={nodes.Circle002_3.geometry} material={materials.Rubber} />
            <mesh name="Circle002_4" geometry={nodes.Circle002_4.geometry} material={materials.DisplayGlass} />
            <mesh name="AppleLogo000" geometry={nodes.AppleLogo000.geometry} material={materials['AppleLogo.004']} position={[0.005, -0.111, -1.795]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.579} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Macbook.glb')
